# Generated by Django 2.2.3 on 2019-07-15 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190714_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['publish_date', '-updated', '-timestamp']},
        ),
    ]
