# Generated by Django 2.2.3 on 2019-07-15 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190714_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['pk', '-publish_date', '-updated', '-timestamp']},
        ),
    ]
