# Generated by Django 2.2.3 on 2019-07-29 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Activate',
            new_name='Active',
        ),
    ]
