# Generated by Django 2.2.3 on 2019-07-29 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_auto_20190728_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['pk', '-publish_date']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Body',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Created',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Post',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
