# Generated by Django 2.2.3 on 2019-10-27 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_mycustomuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCustomUser',
        ),
    ]
