# Generated by Django 2.2.3 on 2020-01-08 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200107_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
