# Generated by Django 2.2.3 on 2019-08-02 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentManager',
        ),
    ]
