# Generated by Django 2.2.3 on 2020-06-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_remove_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=120),
        ),
    ]
