# Generated by Django 2.2.3 on 2019-08-11 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='owner',
            new_name='user',
        ),
    ]
